#!/bin/bash
#/home/alireza/intelFPGA_lite/17.1/modelsim_ase/bin/vsim  -do model.tcl
#/home/alireza/altera/13.0sp1/modelsim_ase/bin/vsim  -do model.tcl
#/home/alireza/altera/modeltech/bin/vsim  -do model.tcl



#questasim
LM_LICENSE="1717@epi03.bsc.es"
VSIM_BIN="/home/alireza/intelFPGA_lite/questa/questasim/bin/vsim"

export LM_LICENSE_FILE=${LM_LICENSE}
export LM_WORK_PLACE=${PRONOC_WORK}/simulation

echo "Start simulation" >&3
$VSIM_BIN  -quiet -64 -do model.tcl
wait 
echo "End of Simulation" >&3
