
    
    
/****************************************************************************
 * pronoc_pkg.sv
 ****************************************************************************/
package pronoc_pkg; 
  
  
localparam V = 4;     // vc_num_per_port
localparam B = 4;     // buffer space :flit per VC    
    
/*TOPOLOGY RELATED PARAMETER*/
// a topology can be defined using at most four localparam 
//    e.g: in mesh:
//    T1: NX, number of node in x dimension T2: NY: number of node in y dimension, T3: NL number of local ports for each router, T4 is not used. 
//    e.g: in fattree:
//    T1: K, umber of last level individual router`s endpoints. T2: L layer number, T3,T4 are not used    
//    e.g: Custom_topology (generated by network-maker:
//    T1: total number of endpoints. T2: total number of routers. T3: maximum number of ports in a router in the topology  
localparam T1= 4;
localparam T2= 4;
localparam T3= 2;
localparam T4= 4;
localparam C = 2;    //    number of flit class 
localparam Fpay = 32;
localparam TOPOLOGY= "MESH"; 
localparam MUX_TYPE= "ONE_HOT";    //"ONE_HOT" or "BINARY"
localparam VC_REALLOCATION_TYPE = "NONATOMIC";// "ATOMIC" , "NONATOMIC"
localparam COMBINATION_TYPE= "COMB_NONSPEC";// "BASELINE", "COMB_SPEC1", "COMB_SPEC2", "COMB_NONSPEC"
localparam FIRST_ARBITER_EXT_P_EN = 1;  
localparam ROUTE_NAME = "XY";
localparam CONGESTION_INDEX = 7;
localparam DEBUG_EN=0;
localparam AVC_ATOMIC_EN= 0;
localparam CONGw = 3; //congestion width per port
localparam ADD_PIPREG_AFTER_CROSSBAR=0;
localparam CVw=(C==0)? V : C * V;
localparam [CVw-1:  0] CLASS_SETTING = {CVw{1'b1}}; // shows how each class can use VCs   
localparam [V-1 :  0] ESCAP_VC_MASK = 4'b1000;  // mask scape vc, valid only for full adaptive
localparam SSA_EN="NO"; // "YES" , "NO"
localparam SWA_ARBITER_TYPE = "RRA";//"RRA","WRRA". RRA: Round Robin Arbiter WRRA weighted Round Robin Arbiter 
localparam WEIGHTw = 7; // WRRA width
localparam MIN_PCK_SIZE=2; //minimum packet size in flits. The minimum value is 1. 
localparam BYTE_EN=0; //0:disable, 1: enable.   Add byte enable (BE) filed to header flit which shows the location of last valid byte in tail flit. It is needed once the send data unit is smaller than Fpay.   
localparam SBP_NUM=2;
localparam Fw = 2+V+Fpay;    //flit width;  

`define     INCLUDE_TOPOLOGY_LOCALPARAM
`include "topology_localparam.v"



localparam
	Vw=  $clog2(V),
	Cw=  (C==0)? 1 : $clog2(C);

/*********************
 * router_interface 
 * *****************/
   	
	typedef struct packed {
		bit hdr_flag;
		bit tail_flag;
		logic [V-1 : 0] vc;
	} flit_append_t;
	
	
	typedef struct packed {
		logic  [RAw-1:  0]  neighbors_r_addr;
	    logic  [Fw-1 :  0]  flit;
		logic  flit_wr;
		logic  [V-1 :  0]  credit;
		logic  [CONGw-1 :  0]  congestion;
	} router_channel_t;
	localparam CHANEL_w = $bits(router_channel_t); 
		
	
/*********************
*    sbp struct
*********************/
	typedef struct packed {
		logic [EAw-1 : 0] dest_e_addr;
		logic ovc_is_assigned;
		logic [Vw-1   : 0] assigned_ovc_bin;
		
	} spb_ivc_t;
	localparam SPB_IVC_w = $bits(spb_ivc_t);
	
	typedef struct packed {
		logic [V-1   	: 0] ovc;
		logic [SBP_NUM-1: 0] flags;
		logic [EAw-1 	: 0] destination;		
	} spb_link_t;
	localparam SPB_LINK_w = $bits(spb_link_t);
	
	
	
	
	typedef struct packed {
		logic 	spb_en;
		logic   [DSTPw-1  :   0] lk_route;
		logic   [V-1 : 0] credit_out;
		logic   [V-1 : 0] buff_space_decreased;
		logic   [V-1 : 0] ovc_is_allocated;
		logic   [V-1 : 0] ovc_is_released;	
	} sbp_ctrl_out_t;	
	
	
	
	
	
 
	
	
	
	
	
    
    
	
	
	
	
	
endpackage : pronoc_pkg


